USE ROLE SYSADMIN;
USE DATABASE DEV_DB;
USE SCHEMA SCHEMACHANGE;

CALL DEPLOY_RBAC_ROLES_FOR_SCHEMA('DEV_DB','CHEESESHOP');

USE ROLE USERADMIN;
GRANT ROLE _DEV_DB_CHEESESHOP_FULL TO ROLE CHEESEMONGER;
GRANT ROLE _DEV_DB_CHEESESHOP_RW TO ROLE SHOPCLERK;
GRANT ROLE _DEV_DB_CHEESESHOP_R TO ROLE CUSTOMER;
